version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: jenkins.io
    path: Linuxcon_2016
    text-resources:
      - path: data/mailing_list_custom.log
        format: flat-key-value
